Fixed initial rendered orientation (angle)
Error: Sometimes 1st orientation was not the one indicated on map
Cause: At manage_input.c, handle_cursor_movement changes the player
	angle depending on the mouse position, this also affects
	the player angle when not touching the mouse after running
	the game (1: compile, 2: move mouse, 3: run game)
Fix: At render_scene.c, draw_scene: added initial set_mouse_pos
	when !graphics->img (for ensuring setting initial position
	of the mouse right only when graphics->img is created